### ISSUE TITLE
Y offset

### ISSUE THREAD

**Issue by bamyazi** [CloneDeath/vox-importer#2] opened 2019-06-22 22:23 UTC
[example.zip](https://github.com/CloneDeath/MagicaVoxel-Importer-with-Extensions/files/3342033/example.zip)

I've had a problem with models not sitting at 0 in the y-axis. Seems to happen when you resize the magicavoxel grid size.

I had to modify the importer the offset the generated vertices by mins.z as follows

	var offset = Vector3(0, -mins.z * scale, 0);

	# Generate geometry
	st.add_color(faces[face])
	for vert in face_meshes[o]:
		st.add_vertex(offset + vox_to_godot.xform(((vert * grow) + face) * scale))

**Comment by CloneDeath** [comment] 2019-06-24 17:44
Hmm. I didn't know you could change the scale in Magica Voxel (makes the import scale kinda redundant, but I'd still like to keep it).

If you could make a pull request with that change, and attach a simple *.vox file that reproduces the issue to this ticket, then I'd gladly test out your fix and accept it.

**Comment by CloneDeath** [comment] 2019-07-02 21:23
Closing issue, since #4 fixes this

**Closed as completed by CloneDeath** 2019-07-02 21:23 UTC
